actions update

diff --git a/.github/workflows/snyk.yml b/.github/workflows/snyk.yml
--- a/.github/workflows/snyk.yml
+++ b/.github/workflows/snyk.yml
@@ -44,27 +44,27 @@ jobs:
         # In this case we want to upload the SAST issues to GitHub Code Scanning
         uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
 
-      #   # For Snyk Open Source you must first set up the development environment for your application's dependencies
-      # - name: Set up JDK 17
-      #   uses: actions/setup-java@v3
-      #   with:
-      #     java-version: '17'
-      #     distribution: 'temurin'
+        # For Snyk Open Source you must first set up the development environment for your application's dependencies
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
 
-      #   # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
-      #   # Use || true to not fail the pipeline
-      # - name: Snyk Code test
-      #   run: snyk code test --sarif-file-output=snyk-code.sarif
-      #   continue-on-error: true
+        # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
+        # Use || true to not fail the pipeline
+      - name: Snyk Code test
+        run: snyk code test --sarif-file-output=snyk-code.sarif
+        continue-on-error: true
 
-      #   env:
-      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
-      #   # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
-      # - name: Snyk Open Source monitor
-      #   run: snyk monitor --all-projects
-      #   env:
-      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
+      - name: Snyk Open Source monitor
+        run: snyk monitor --all-projects
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
         # Build/pull the docker image from GHCR for testing
       - name: Log into registry ${{ env.REGISTRY }}\
@@ -87,10 +87,8 @@ jobs:
         with:
           context: .
           pull: true
-          push: false
           load: true
           tags: ${{ steps.meta.outputs.tags }}
-          # tags: ticketmaster
           cache-from: type=gha
           cache-to: type=gha,mode=max     
          
@@ -103,8 +101,8 @@ jobs:
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
-      #   # Push the Snyk Code results into GitHub Code Scanning tab
-      # - name: Upload result to GitHub Code Scanning
-      #   uses: github/codeql-action/upload-sarif@v2
-      #   with:
-      #     sarif_file: snyk-code.sarif
+        # Push the Snyk Code results into GitHub Code Scanning tab
+      - name: Upload result to GitHub Code Scanning
+        uses: github/codeql-action/upload-sarif@v2
+        with:
+          sarif_file: snyk-code.sarif
